# Generated by Django 5.1.6 on 2025-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_plant_alter_customuser_email_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(choices=[('leaf rust', 'Leaf Rust'), ('dahon', 'Dahon'), ('amag', 'Amag'), ('insecto', 'Insecto'), ('good', 'Good')], max_length=20),
        ),
    ]
