# Generated by Django 5.1.6 on 2025-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_plant_plant_number_plant_symptoms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_number', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('leaf rust', 'Leaf Rust'), ('dahon', 'Dahon'), ('amag', 'Amag'), ('insecto', 'Insecto'), ('good', 'Good')], max_length=20)),
                ('symptoms', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='plant_number',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='symptoms',
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(max_length=255),
        ),
    ]
