# Generated by Django 5.1.6 on 2025-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_plantinventory_remove_plant_plant_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
