# Generated by Django 5.1.6 on 2025-03-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='id',
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
