# Generated by Django 5.1.6 on 2025-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_plant_id_alter_plant_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='location',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_number',
            field=models.IntegerField(default=0),
        ),
    ]
