# Generated by Django 5.1.7 on 2025-04-22 01:18

import dashboard.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_plant_location_plant_plant_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Tree', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('healthy_percentage', models.FloatField(default=0)),
                ('leaf_rust_percentage', models.FloatField(default=0)),
                ('powdery_mildew_percentage', models.FloatField(default=0)),
                ('overall_health', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tree Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeafImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dashboard.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('healthy_confidence', models.FloatField(default=0)),
                ('leaf_rust_confidence', models.FloatField(default=0)),
                ('powdery_mildew_confidence', models.FloatField(default=0)),
                ('tree_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_images', to='dashboard.treeanalysis')),
            ],
        ),
    ]
