# Generated by Django 5.1.7 on 2025-06-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_treeanalysis_leafimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='tree_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.treeanalysis'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(default='undetected', max_length=255),
        ),
    ]
