# Generated by Django 5.1.7 on 2025-06-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_plant_tree_analysis_alter_plant_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeanalysis',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tree_analyses', to='dashboard.plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='tree_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_plant', to='dashboard.treeanalysis'),
        ),
    ]
