# Generated by Django 5.1.7 on 2025-06-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_treeanalysis_plant_alter_plant_tree_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeanalysis',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_analyses', to='dashboard.plant'),
        ),
    ]
