# Generated by Django 5.1.7 on 2025-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafimage',
            name='dried_leaf_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='dried_leaf_confidence',
            field=models.FloatField(default=0),
        ),
    ]
