# Generated by Django 5.2.4 on 2025-08-07 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_leafimage_dried_leaf_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='Pest Detection Session', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('total_processed', models.IntegerField(default=0)),
                ('no_pest_count', models.IntegerField(default=0)),
                ('pest_count', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('uncertain_count', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pest Detection Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('prediction', models.CharField(max_length=50)),
                ('original_prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('is_low_confidence', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('adristyrannus_confidence', models.FloatField(default=0.0)),
                ('aphids_confidence', models.FloatField(default=0.0)),
                ('beetle_confidence', models.FloatField(default=0.0)),
                ('bugs_confidence', models.FloatField(default=0.0)),
                ('mites_confidence', models.FloatField(default=0.0)),
                ('weevil_confidence', models.FloatField(default=0.0)),
                ('whitefly_confidence', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.pestdetectionsession')),
            ],
        ),
    ]
