# Generated by Django 5.1.7 on 2025-08-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_pestdetectionsession_pestdetectionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
