# Generated by Django 5.1.7 on 2025-08-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_plant_status_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='status_percentage',
        ),
    ]
