# Generated by Django 5.1.7 on 2025-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_plant_status_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafimage',
            name='fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
