# Generated by Django 5.1.7 on 2025-09-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_leafimage_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leafimage',
            name='fingerprint',
        ),
    ]
