# Generated by Django 5.2.7 on 2025-11-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_leafimage_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeanalysis',
            name='dried_leaf_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='dried_leaf_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='healthy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='leaf_rust_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='powdery_mildew_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeanalysis',
            name='total_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
