# Generated by Django 5.2.7 on 2025-11-03 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_treeanalysis_dried_leaf_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
