# Generated by Django 5.2.7 on 2025-11-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_email_verified'),
        ('dashboard', '0022_alter_treeanalysis_created_at'),
    ]

    operations = [
    ]
