# Generated by Django 5.2.7 on 2025-12-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_customuser_email_verified_and_more'),
    ]

    operations = [
    ]
